version: 2.1

orbs:
  kaocha: lambdaisland/kaocha@0.0.1:first
  clojure: lambdaisland/clojure@0.0.1:first

commands:
  checkout_and_run:
    parameters:
      clojure_version:
        type: string
    steps:
      - checkout
      - clojure/with_cache:
          cache_version: << parameters.clojure_version >>
          steps:
            - kaocha/execute:
                args: "--reporter documentation --plugin cloverage --codecov"
                clojure_version: << parameters.clojure_version >>
      - kaocha/upload_codecov

jobs:
  java-8-clojure-1_9:
    executor: clojure/openjdk8
    steps: [{checkout_and_run: {clojure_version: "1.9.0"}}]

  java-8-clojure-1_10:
    executor: clojure/openjdk8
    steps: [{checkout_and_run: {clojure_version: "1.10.0"}}]

workflows:
  kaocha_test:
    jobs:
      - java-8-clojure-1_9
      - java-8-clojure-1_10